### PR TITLE
Add the "Membership and Subscriptions" team

### PR DESCRIPTION
**Pull request by rtyley**
@philwills sold it to me :-)

cc @philmcmahon

### CODE REVIEW

**Comment by philmcmahon** [comment]
Sorry for the slow response on this, I somehow missed it!

**Comment by philmcmahon** [comment]
This has been deployed and the bucket updated.

**Comment by philmcmahon** [comment]
I've also given the membership AWS account access to the s3 bucket so you should be good to go.

**Comment by rtyley** [comment]
Great! cc @paulbrown1982

**Pull request merged**
